project_id = "oikpwuraixlnjvyrmnwx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[graphql]
enabled = true
port = 54329

[inbound_smtp]
enabled = false
port = 54330
emails_from_external = true

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
image_transformation_enabled = true

[auth]
enabled = true
port = 54325
external_providers = []

[edge_functions]
enabled = true
port = 54326

[functions.get-weather]