# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "oikpwuraixlnjvyrmnwx"

[functions.sitemap]
verify_jwt = false

[functions.google-clothing-search]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.get-weather-multiple]
verify_jwt = false

[functions.get-local-services]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.security-logger]
verify_jwt = false

[functions.reset-wardrobe]
verify_jwt = true