project_id = "oikpwuraixlnjvyrmnwx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[graphql]
enabled = true
port = 54329

[inbound_smtp]
enabled = false
port = 54330
emails_from_external = true

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
image_transformation_enabled = true

[auth]
enabled = true
port = 54325
external_providers = []

[edge_functions]
enabled = true
port = 54326

[functions.get-weather]
verify_jwt = false

[functions.get-weather-multiple]
verify_jwt = false

[functions.get-local-services]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.security-logger]
verify_jwt = false

[functions.reset-wardrobe]
verify_jwt = true